- alias: "Turn on outside lights before sunset"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.outside_lights
- alias: "Turn off outside lights at midnight"
  trigger:
    platform: time
    after: "00:00:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.outside_lights
- alias: "Turn on outside lights in early morning"
  trigger:
    platform: time
    after: "06:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: light.outside_lights
- alias: "Turn off outside lights after sunrise"
  trigger:
    platform: sun
    event: sunrise
    offset: "+00:45:00"
  action:
    service: homeassistant.turn_off
    entity_id: light.outside_lights
- alias: "Notify when garage door is open and not home"
  trigger:
    platform: state
    entity_id: sensor.house_garage_door
    to: 'open'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'device_tracker.hansen_jasonnexus6p'
        state: 'not home'
      - condition: state
        entity_id: 'device_tracker.hansen_luisaiphone'
        state: 'not home'
  action:
    service: notify.pushbullet
    data:
      message: "House garage door was opened"
      title: "House garage door was opened"
- alias: "Notify when garage door open for a minute"
  trigger:
    platform: state
    entity_id: sensor.house_garage_door
    to: 'open'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      message: "House garage door has been open for 1 minute"
      title: "House garage door has been open for 1 minute"
- alias: "Notify when back door open and not home"
  trigger:
    platform: state
    entity_id: sensor.back_door
    to: 'open'
  condition:
    condition: state
    entity_id: group.phones
    state: 'not home'
  action:
    service: notify.pushbullet
    data:
      message: "Back door was opened"
      title: "Back door was opened"
- alias: "Notify when back door open for a minute"
  trigger:
    platform: state
    entity_id: sensor.back_door
    to: 'open'
    for:
      minutes: 1
  action:
    service: notify.pushbullet
    data:
      message: "Back door has been open for 1 minute"
      title: "Back door has been open for 1 minute"
- alias: "Notify when front motion active and not home"
  trigger:
    platform: state
    entity_id: sensor.back_door
    to: 'active'
  condition:
    condition: state
    entity_id: group.phones
    state: 'not home'
  action:
    service: notify.pushbullet
    data:
      message: "There was motion detected by the front motion sensor"
      title: "There was motion detected by the front motion sensor"
- alias: New version notification
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.pushbullet_jason
    data:
      title: 'New Home Assistant Release'
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
- alias: "Bedroom Chromecast paused/stopped"
  trigger:
    platform: state
    entity_id: media_player.bedrooom_chromecast
    from: 'playing'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_normal
- alias: "Bedroom Chromecast playing"
  trigger:
    platform: state
    entity_id: media_player.bedrooom_chromecast
    to: 'playing'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_dim
- alias: "Turn on master bedroom lights in the evening"
  trigger:
    platform: sun
    event: sunset
  condition:
    condition: state
    entity_id: group.master_bedroom
    state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.master_bedroom_dim
- alias: "Turn off master bedroom lights at midnight if nobody's there"
  trigger:
    platform: time
    after: "00:00:00"
  condition:
    condition: state
    entity_id: binary_sensor.bobito_occupancy
    state: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: group.master_bedroom
