homeassistant:
  name: Hansen Home
  latitude: 41.0859
  longitude: -111.9022
  elevation: 1577
  unit_system: imperial
  time_zone: America/Denver

  customize:
    climate.bobina:
      friendly_name: Ecobee Thermostat
    sensor.bobina_humidity:
      friendly_name: Humidity 
    sensor.bobina_temperature:
      friendly_name: Main Floor Temperature 
    sensor.bobito_temperature:
      friendly_name: Upstairs Temperature 
    sensor.yweather_current:
      friendly_name: Current Conditions
    sensor.yweather_temperature:
      friendly_name: Current Temperature
    sensor.yweather_temperature_max:
      friendly_name: Today's High
    sensor.yweather_temperature_min:
      friendly_name: Today's Low
    sensor.yweather_humidity:
      friendly_name: Humidity
    sensor.yweather_wind_speed:
      friendly_name: Wind Speed

group:
  default_view:
    view: yes
    entities:
      - group.indoor_climate
      - group.weather
  indoor_climate:
    name: Indoor Climate
    entities:
      - climate.bobina
      - sensor.bobina_temperature
      - sensor.bobito_temperature
      - sensor.bobina_humidity
  server_info:
    name: Server Info
    entities:
      - sensor.since_last_boot
      - sensor.cpu_use
      - sensor.ram_use
      - sensor.ram_free
  weather:
    name: Weather
    entities:
      - sensor.yweather_current
      - sensor.yweather_temperature
      - sensor.yweather_temperature_max
      - sensor.yweather_temperature_min
      - sensor.yweather_humidity
      - sensor.yweather_wind_speed
      - sun.sun
  master_bedroom:
    name: Master Bedroom
    view: yes
    entities:
      - media_player.bedroom_chromecast
  office:
    name: Office
    view: yes
    entities: group.server_info

frontend:

http:
  api_password: !secret http_password

updater:

discovery:

conversation:

history:

logbook:

sun:

sensor:
  - platform: yr
  - platform: plex
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: memory_free
      - type: processor_use
      - type: since_last_boot
  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temp_min
      - temp_max
      - wind_speed
      - pressure
      - visibility
      - humidity
      - temperature

ecobee:
  api_key: !secret ecobee_api_key 

ifttt:
  key: !secret ifttt_api_key

media_player:
  - platform: plex
  - platform: cast

device_tracker:
  - platform: netgear
    host: 192.168.0.1
    port: 80
    username: admin
    password: !secret router_password
