homeassistant:
  name: Home
  latitude: 41.0859
  longitude: -111.9022
  elevation: 1577
  unit_system: imperial
  time_zone: America/Denver
  customize: !include customize.yaml

frontend:
updater:
discovery:
conversation:
history:
logbook:
sun:

http:
  api_password: !secret http_password

ecobee:
  api_key: !secret ecobee_api_key

ifttt:
  key: !secret ifttt_api_key

mqtt:
  broker: 192.168.0.101
  port: 1883
  client_id: home-assistant
  protocol: 3.1
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1

automation: !include automations.yaml
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
notify: !include notify.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
