- platform: nmap_tracker
  hosts: 192.168.0.1/24
  consider_home: 180
  track_new_devices: false

- platform: mqtt
  devices:
    hansen_jasonnexus6p: "smartthings/Jason Hansen's Android/presence"
    hansen_luisaiphone: "smartthings/Luisa's iPhone/presence"
