- platform: mqtt
  name: "House Garage Door"
  state_topic: "smartthings/House Garage Door/contact"
  payload_on: "closed"
  payload_off: "open"
  sensor_class: opening
- platform: mqtt
  name: "House Garage Door Temperature"
  state_topic: "smartthings/House Garage Door/temperature"
  unit_of_measurement: "°F"
- platform: mqtt
  name: "Back Door"
  state_topic: "smartthings/Back Door/contact"
  payload_on: "closed"
  payload_off: "open"
  sensor_class: opening
- platform: mqtt
  name: "Back Door Temperature"
  state_topic: "smartthings/Back Door/temperature"
  unit_of_measurement: "°F"
- platform: mqtt
  name: "Front Motion Sensor"
  state_topic: "smartthings/Front Motion Sensor/motion"
  payload_on: "active"
  payload_off: "inactive"
  sensor_class: motion
- platform: mqtt
  name: "Front Motion Sensor Temperature"
  state_topic: "smartthings/Front Motion Sensor/temperature"
  unit_of_measurement: "°F"
- platform: mqtt
  name: "Carbon Monoxide Detector"
  state_topic: "smartthings/Smoke and CO Alarm/carbonMonoxide"
  payload_on: "detected"
  payload_off: "clear"
  sensor_class: smoke
- platform: mqtt
  name: "Smoke Detector"
  state_topic: "smartthings/Smoke and CO Alarm/smoke"
  payload_on: "detected"
  payload_off: "clear"
  sensor_class: smoke
- platform: yr
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: since_last_boot
- platform: yweather
  monitored_conditions:
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature
